/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unicam.cs.metodologie_di_programmazione.formula1;

import java.io.IOException;


/**
 * Classe che rappresenta una partita del gioco Formula1.
 *
 * Per avviare ed assistere ad una partita tra Giocatori Bot è
 * sufficiente inserire i nomi dei file che si vogliono utilizzare
 * all'interno dei metodi LeggiMappa e LeggiBot in maniera coerente
 * ed infine avviare la classe Partita.
 *
 * @author Davide Cabitza
 *
 */


public class Partita {

    /**
     * Avviare il file "Partita.java" per assistere ad una partita di Fromula 1 tra Giocatori Bot
     *
     * N.B ASSICURARSI DI AVER INSERITO I FILE CORRETTAMENTE
     *
     * @throws IOException          se scaturisce un errore all'avvio della partita
     */
    public static void main(String[] args) throws IOException {

        /**
         * Inserire il nome del File con la Mappa di gioco da utilizzare.
         */
        LeggiMappa leggiMappa = new LeggiMappa("mappa.txt");

        /**
         * Inserire il nome del File con i nomi dei Giocatori Bot da utilizzare.
         */
        LeggiBot leggiBot = new LeggiBot("giocatori.txt");

        /**
         * Creare il motore di gioco passando gli oggetti precedentemente ricavati.
         */
        Engine motoreDiGioco = new Engine(leggiMappa, leggiBot);

        /**
         * Avvia la Partita".
         */
        motoreDiGioco.startPartita();


    }



}
